### ISSUE TITLE
Unused `import secrets` in manager breaks python 3.5 support

### ISSUE THREAD

**Issue by Paul-Andre** [battlecode/battlecode-2018#129]
https://github.com/battlecode/battlecode-2018/blob/55ba2d8301bf521e65e070daf7378313cb5babc1/battlecode-manager/player_sandboxed.py#L8
Are you eventually planning to use `secret`? That's a 3.6 only library.

It's nice to not need to install python 3.6 just to run the scaffold when a lot of people already have python 3.5 already on their computer.

**Comment by kazimuth** [comment]
Fixed in next release
